In [1]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
df = datasets.load_iris(as_frame=True).frame

In [16]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [17]:
df.shape

(150, 5)

In [3]:
df.isnull().sum()
df.shape
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [4]:
X = df.drop("target", axis=1)
y = df["target"]

In [5]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
# Model
svc = SVC()
svc.fit(X_train_scaled, y_train)

SVC()

In [9]:
y_pred = svc.predict(X_test_scaled)

In [10]:
# Evaluate
from sklearn.metrics import accuracy_score, classification_report

print("accuracy: ", accuracy_score(y_test, y_pred))
print("classification report: \n ", classification_report(y_test, y_pred))

accuracy:  0.9333333333333333
classification report:
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [11]:
# Linear kernel

svc = SVC(kernel="linear")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)

print("accuracy: ", accuracy_score(y_test, y_pred))

accuracy:  0.9111111111111111

In [12]:
# Polynomial kernel

svc = SVC(kernel="poly")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)

print("accuracy: ", accuracy_score(y_test, y_pred))

accuracy:  0.8666666666666667

In [13]:
# Sigmoid kernel

svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)

print("accuracy: ", accuracy_score(y_test, y_pred))

accuracy:  0.9111111111111111

In [14]:
C_vals = [0.5, 1, 2, 3, 4, 5]

for c_val in C_vals:
    svc = SVC(C=c_val, kernel="rbf")
    svc.fit(X_train_scaled, y_train)

    y_pred = svc.predict(X_test_scaled)

    print("C = ", c_val, "& accuracy: ", accuracy_score(y_test, y_pred))

C =  0.5 & accuracy:  0.9111111111111111
C =  1 & accuracy:  0.9333333333333333
C =  2 & accuracy:  0.9111111111111111
C =  3 & accuracy:  0.9111111111111111
C =  4 & accuracy:  0.9333333333333333
C =  5 & accuracy:  0.9333333333333333